In [1]:
#1 what is Numpy and why it is important for datascience?
Numpy is python library for numerical operation.
#2Expalin difference between python list and numpy array?
NumPy arrays are stored only one type of data.( for large datasets because they store data in contiguous memory blocks) 
Python list storerd multiple type of data.

In [11]:
#3How do yo can create numpy arrray of zeros with  a specific shape?
import numpy as np
array=np.zeros((4,6))
print(array)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [15]:
#4What are the common datatype in nmpy?
int,float,doble,string etc....

In [23]:
#5(a)How do yo perform element_wise addition,subtraction,multiplication,division in Numpy arrays?
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 + arr2
print(result)  

[5 7 9]


In [31]:
#5(b)
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 - arr2
print(result)

[-3 -3 -3]


In [27]:
#5(c)
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 * arr2
print(result)

[ 4 10 18]


In [33]:
#5(d)
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 / arr2
print(result)

[0.25 0.4  0.5 ]


In [ ]:
#6Explain the concept of numpy slicing in Numpy?
Slicing in NumPy issed to extracting range of data from specific portion.
This works for both one-dimensional (1D) and multidimensional arrays                                                                                                                        

In [49]:
#6
import numpy as np
arr=np.array([10,20,30,40,50])
por=arr[1:3]
print(por)

[20 30]


In [ ]:
#7How do you find mean,median,mode in numpy array?
Mean:sum of all number in dataset 
Median:middle value of dataset
Mode:most repeated dataset

In [53]:
#7(a)
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
mean = np.mean(arr)
print( mean)

3.0


In [55]:
#7(b)
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
median = np.median(arr)
print(median)

3.0


In [79]:
#7(c)
import numpy as np
from scipy import stats
arr = np.array([1, 2, 3, 4, 5,2])
mode = stats.mode(arr)
print(mode)

ModeResult(mode=2, count=2)


In [ ]:
#8what is broadcoasting in numpy  and how does it work?
Broadcasting in NumPy lets arrays with different shapes work together in operations
by automatically adjusting their shapes without copying data.

In [81]:
#8
import numpy as np
arr = np.array([1, 2, 3])
scalar = 5
# Broadcasting the scalar to match the array
result = arr + scalar
print(result) 

[6 7 8]


In [ ]:
#9what is pandas and what are its key data structure?
Pandas is a powerful Python library used for data manipulation and anaysis.
This handling structured data for time series and tabular data.

In [83]:
#9(Series)
import pandas as pd
series = pd.Series([1, 2, 3, 4])
#9(DataFrame)
df = pd.DataFrame({
    "Name": ["Ezzan, "Bilal", "Charly"],
    "Age": [25, 30, 35]
}).....

In [87]:
#10How do you import data from csv file into a pandas DataFrame?
import pandas as pd
df = pd.read_csv('file_path.csv')
print(df)

In [18]:
#11(a)How do you select specifice column or rows from DataFrame?
import pandas as pd
data = {
    "A": [1, 2, 3],
    "B": [4, 5, 6],
    "C": [7, 8, 9]
}
df = pd.DataFrame(data)
#single column
column_a = df["C"]
#select single colmns
column_a = df.loc[:,"C"]
print(column_a)

0    7
1    8
2    9
Name: C, dtype: int64


In [22]:
#(b)
import pandas as pd
data = {
    "A": [1, 2, 3],
    "B": [4, 5, 6],
    "C": [7, 8, 9]
}
df = pd.DataFrame(data)
#multiple column 
columns_ab = df[["A", "B"]]
# Select multiple columns
columns_ab = df.loc[:, ["A", "B"]]
print(columns_ab)

   A  B
0  1  4
1  2  5
2  3  6


In [ ]:
#12.(A)Explain the difference between the loc and iloc indexers in Pandas.
*loc work with labels.
->Label-based (row/column names)
->Includes the end of the range
*iloc work with positions.
->Position-based (integer indices)
->Excludes the end of the range                                                                    

In [1]:
#12(A)
import pandas as pd
data = {"A": [1, 2, 3], 
        "B": [4, 5, 6], 
        "C": [7, 8, 9]}
df = pd.DataFrame(data, index=["row1", "row2", "row3"])
# Using loc
print(df.loc["row2", "B"])  

5


In [28]:
#12(A)
import pandas as pd
data = {"A": [1, 2, 3], 
        "B": [4, 5, 6], 
        "C": [7, 8, 9]}
df = pd.DataFrame(data, index=["row1", "row2", "row3"])
#Using iloc
print(df.iloc[1, 2]) 

8


In [ ]:
#13.How do you handle missing values (NaN) in a DataFrame?
isnull() ,notnull().
fillna() ,dropna()

In [5]:
#13(A)
import pandas as pd
import numpy as np
data = {"A": [1, 2,0 , 4],
        "B": [np.nan, 2, 3, 4], 
        "C": [1, np.nan, np.nan, 4]}
df = pd.DataFrame(data)
df=df.dropna(axis=0)
print(df)

   A    B    C
3  4  4.0  4.0


In [3]:
#13(A)
import pandas as pd
import numpy as np
data = {"A": [1, 2,0 , 4],
        "B": [0, 2, 3, 4], 
        "C": [1, np.nan, np.nan, 4]}
df = pd.DataFrame(data)
df = df.fillna(0)
print(df)

   A  B    C
0  1  0  1.0
1  2  2  0.0
2  0  3  0.0
3  4  4  4.0


In [7]:
#14.How do you filter rows in a DataFrame based on conditions?
#(like <,>,<=,>=)
import pandas as pd
data = {"A": [1, 2, 3, 4, 5],
        "B": [5, 4, 3, 2, 1]}
df = pd.DataFrame(data)
# Filter rows where A is greater than 3
filtered_df = df[df["A"] > 3]
print(filtered_df)

   A  B
3  4  2
4  5  1


In [9]:
#15.How do you group data in a DataFrame and perform aggregations?
import pandas as pd
data = {"Category": ["A", "B", "A", "B", "A", "B"],
        "Value": [10, 20, 30, 40, 50, 60]}
df = pd.DataFrame(data)
group_df = df.groupby("Category")["Value"].sum()
print(group_df)

Category
A     90
B    120
Name: Value, dtype: int64


In [69]:
#16.What is the difference between concat and merge in Pandas?
#(A)concate
import pandas as pd
df1 = pd.DataFrame({"A": [1, 2],
                    "B": [3, 4]})
df2 = pd.DataFrame({"A": [5, 6], 
                    "B": [7, 8]})
result = pd.concat([df1, df2])
print(result)


   A  B
0  1  3
1  2  4
0  5  7
1  6  8


In [75]:
#16(A)
#merge
import pandas as pd
df1 = pd.DataFrame({"ID": [1, 2], 
                    "A": [3, 4]})
df2 = pd.DataFrame({"ID": [1, 2], 
                    "B": [5, 6]})
result = pd.merge(df1, df2, on="ID")
print(result)

   ID  A  B
0   1  3  5
1   2  4  6


In [ ]:
'''#17.You have two DataFrames with some overlapping columns. Describe how 
you would perform an outer join and explain the significance of an outer join 
compared to an inner join.'''
Outer Join: Keeps all rows, filling with NaN where there are no matches.
Inner Join: Only keeps rows with matching values in both DataFrames.


In [81]:
#17(A)outer join:
import pandas as pd
df1 = pd.DataFrame({"ID": [1, 2, 3], 
                    "A": [10, 20, 30]})
df2 = pd.DataFrame({"ID": [2, 3, 4], 
                    "B": [200, 300, 400]})
outer_join = pd.merge(df1, df2, on="ID", how='outer')
print(outer_join)

   ID     A      B
0   1  10.0    NaN
1   2  20.0  200.0
2   3  30.0  300.0
3   4   NaN  400.0


In [11]:
#17(A)Inner join:
import pandas as pd
df1 = pd.DataFrame({"ID": [1, 2, 3], 
                    "A": [10, 20, 30]})
df2 = pd.DataFrame({"ID": [2, 3, 4], 
                    "B": [200, 300, 400]})
inner_join = pd.merge(df1, df2, on="ID", how='inner')
print(inner_join)

   ID   A    B
0   2  20  200
1   3  30  300


In [89]:
'''#18.Explain the concept of vectorization in NumPy. How does it improve the 
performance of numerical computations?'''
#concept:
import numpy as np
arr = np.array([1, 2, 3, 4])
result = []
for i in arr:
    result.append(i + 3)
print(result)

[4, 5, 6, 7]


In [104]:
#18(A)Performance:
import numpy as np
import time
arr1 = np.random.rand(1000000)
arr2 = np.random.rand(1000000)
start = time.time()
result_vectorized = arr1 + arr2
print( "vectorized time:",time.time() - start)
start = time.time()
result_loop = [arr1[i] + arr2[i] for i in range(len(arr1))]
print("Loop time:", time.time() - start)

vectorized time: 0.009949445724487305
Loop time: 0.8572535514831543


In [1]:
'''#19.You have a DataFrame with a column containing dates. How would you: (a) 
Convert the date column to a datetime object? (b) Extract the year, month, 
and day from the dates? (c) Filter the DataFrame to select data from a specific 
date range'''
#(a)DateTime
import pandas as pd
data = {'Date': ['2021-01-01', 
                 '2021-02-01',
                 '2021-03-01']}
df = pd.DataFrame(data)
df['Date'] = pd.to_datetime(df['Date'])
print(df)


        Date
0 2021-01-01
1 2021-02-01
2 2021-03-01


In [11]:
#(b)Year,Month,Day:
import pandas as pd
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
df['Day'] = df['Date'].dt.day
print(df)

        Date  Year  Month  Day
0 2021-01-01  2021      1    1
1 2021-02-01  2021      2    1
2 2021-03-01  2021      3    1


In [9]:
#(c)Fliter the DataFrame from data Range:
import pandas as pd
start_date = '2021-01-01'
end_date = '2021-02-01'
filtered_df = df[(df['Date'] >= start_date) & (df['Date'] <= end_date)]
print(filtered_df)

        Date  Year  Month  Day
0 2021-01-01  2021      1    1
1 2021-02-01  2021      2    1


In [13]:
'''#20..Describe a scenario where you would use a GroupBy operation in Pandas, 
and explain how you would perform an aggregation (e.g., calculate the 
average) within each group'''
#GroupBy in Pandas groups data based on a column and calculates things like average or total for each group to find pattern.
import pandas as pd
data = { "Store": ["A", "B", "A", "B", "A", "B"],
         "Date": ['2023-01-01', '2023-01-01', '2023-01-02', '2023-01-02', '2023-01-03', '2023-01-03'],
        "Sales Amount": [150, 200, 180, 250, 200, 300]
}
df = pd.DataFrame(data)
# Store and calculate the average sales amount
grouped = df.groupby("Store")["Sales Amount"].mean()
print(grouped)


Store
A    176.666667
B    250.000000
Name: Sales Amount, dtype: float64
